### PR TITLE
translations

### PR DESCRIPTION
**Pull request by HaleyHalcyon**

### CODE REVIEW

**Comment by Tanza3D** [comment]
would appreciate if you could just exclude machine translated ones entirely until we can get real translators :pray:

**Comment by Tanza3D** [comment]
russian
`Вы уверены, что хотите заблокировать {handle} ({did})? Вам нужно будет обновить страницу, чтобы увидеть изменения.`

**Comment by Tanza3D** [comment]
dutch
`Weet je zeker dat je {handle} ({did}) wilt blokkeren? Je zult de pagina moeten herladen om de verandering te zien.`

**Comment by HaleyHalcyon** [comment]
> dutch `Weet je zeker dat je {handle} ({did}) wilt blokkeren? Je zult de pagina moeten herladen om de verandering te zien.`

Dutch is not supported on Bluesky, so it will never be chosen. Do you still want it in the script?
image

**Comment by Tanza3D** [comment]
i'd say to add it in just in case! you never know when dutch'll be added to bluesky.. maybe i will ask my friend to translate it! ^^

**Comment by Tanza3D** [comment]
^ is this good to be merged or do you have more changes you'd want to make?

**Comment by HaleyHalcyon** [comment]
Should be fine to merge

**Pull request merged**
